name: dummy-workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_call:

jobs:
  dummy_workflow:
    name: Discovery OS
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on:
        - ubuntu-20.04
    steps:      
      - name: view OS
        id: os
        run: |
          cat /etc/os-release
